### ISSUE TITLE
Could not find tiles

### ISSUE THREAD

**Issue by weteamsteve** [plhearn/tileEditor#1]
After compiling and trying to open Map001.xml I'm getting

{"Could not find file 'C:\Users\Steven\Desktop\tileEditor-master\bin\x86\Debug\ForestTiles'.":"C:\Users\Steven\Desktop\tileEditor-master\bin\x86\Debug\ForestTiles"}

I also copy the three tiles files into that location and it still doesnt work. I was going to take away .png from the files but I am wondering how you use the program instead of me changing it.

**Comment by plhearn** [comment]
Yes I've made some changes to how it loads the xml files since I've been working with those maps.  You'll need to edit the texture name in the map xml file and add .png on the end.  Then it should load if the texture file is there.  Removing the .png from the filename should work too.
